services:
  app:
    image: ghcr.io/evs-gis/glourbee-ui:1.1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app/ui:ro
      - ./glourbee:/app/glourbee:ro